### ISSUE TITLE
Command Todo List

### ISSUE THREAD

**Issue by habitu** [toontownaustralia/IRCBot#1]
- [x] Authorise Bot **Needs to be fixed**
- [ ] Ban User
- [ ] Kick User
- [ ] Voice Moderator
- [ ] OP Developer
- [ ] Get a Server Status
- [ ] Get Invasion Status
- [ ] Latest News Thread
- [ ] Send RPC Methods
