### ISSUE TITLE
Enhancement Todo List

### ISSUE THREAD

**Issue by habitu** [toontownaustralia/IRCBot#2]
- [ ] Remove all swearing in chat
- [ ] Create a data dictionary which will remove any unwanted nicknames
- [ ] Timed bot update
- [ ] Alert the users when something has changed.
